version: '2'
services:
    gonisoftware-app:
        image: gonisoftware
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gonisoftware-mysql:3306/gonisoftware?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gonisoftware-elasticsearch:9300
        ports:
            - 8080:8080
    gonisoftware-mysql:
        extends:
            file: mysql.yml
            service: gonisoftware-mysql
    gonisoftware-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gonisoftware-elasticsearch
